name: tinder_app_flutter
description: Tinder app made with Flutter

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  numberpicker: ^2.1.1
  image_picker: ^0.8.5+3
  firebase_storage: ^10.3.7
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  cloud_firestore: ^3.4.6
  percent_indicator: ^4.2.2
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-SemiBold.ttf
        - asset: fonts/Nunito-Bold.ttf
